### ISSUE TITLE
求问大佬！下载速度过于慢怎么办！

### ISSUE THREAD

**Issue by Max66888** [unknown-o/download-station#6]
求问大佬！下载速度过于慢怎么办！
我本地服务器带宽是100M的，但是通过下载站速度就非常非常慢，只有1Mbps不到而且延迟很高！
求救！非常想要这个PHP搭建的直链下载站挂载本地磁盘！！！

**Comment by unknown-o** [comment]
可以尝试修改config.php中的下载限速
