### ISSUE TITLE
首页有报错index.php line 5

### ISSUE THREAD

**Issue by QQ169876** [unknown-o/download-station#7]
在原有第5行插入

`if (empty($_GET['f'])) $_GET['f']="/";`

就好了。。。

另外，如果图片能显示个小小的预览就更好了。：）

**Comment by unknown-o** [comment]
关于首页报错的问题，确实存在此问题，将在下个版本修复
关于图片预览的话可以考虑更新，即点击图片展示图片灯箱

**Comment by QQ169876** [comment]
要做预览的话，建议考虑下缩略图，我自己尝试加了个显示图片的功能，但就发现我测试的图有点大21M,哈，结果就是我把图删除了。。。
![image](https://user-images.githubusercontent.com/60913853/236655451-248c6449-f5e7-4a21-ba23-26e42d3aaa17.png)

**Comment by Whirity404** [comment]
我建议还是鼠标移上去显示图片那种，也就是鼠标移上去再加载，这样可以省流量
